controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yaml"
