#controllers:
#    resource: ../../src/Controller/
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yaml"

cms_bundle:
    resource: "@CMSBundle/Resources/config/routing.yaml"

ecommerce_bundle:
    resource: "@ECommerceBundle/Resources/config/routing.yaml"

media_bundle:
    resource: "@MediaBundle/Resources/config/routing.yaml"

page_bundle:
    resource: "@PageBundle/Controller/"
    type: annotation
