ecommerce_admin:
  resource: "@ECommerceBundle/Controller/Administration"
  type:     annotation
  prefix:   /admin

ecommerce_frontend:
  resource: "@ECommerceBundle/Controller/FrontEnd"
  type:     annotation